version: '3'

services:
  mongodb:
    image: mobilecoach/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mc
      - MONGO_INITDB_ROOT_PASSWORD=mc
      - MONGO_INITDB_DATABASE=mc

  tomcat_server:
    image: mobilecoach/tomcat
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb
    links:
      - mongodb  
    volumes:
      - .:/mc_data  